[window.padding]
x = 20
y = 20

[window]
opacity = 0.85

[font]
size = 13.0

[font.normal]
family = "Xanh Mono"
style = "Regular"

[font.bold]
family = "Xanh Mono"
style = "Bold"

[font.offset]
x = 1
y = 0

[colors.primary]
background = '#0d0d0d'
